name: 'IPFS-Pinning-DNSlink'
description: 'GitHub Action for uploading files to IPFS. Supports pinning services and dnslink publishing to Vercel DNS'
branding:
  icon: 'box'
  color: 'yellow'
inputs:
  path:
    description: 'Directory path to upload'
    required: true
  service:
    description: 'Type of target service to upload. Supported services [ipfs, pinata, infura]'
    required: false
    default: 'ipfs'
  timeout:
    description: 'Request timeout'
    required: false
    default: 60000
  verbose:
    description: 'Level of verbosity'
    required: false
    default: false
  host:
    description: '[ipfs] IPFS host'
    required: false
    default: 'ipfs.komputing.org'
  port:
    description: '[ipfs] IPFS port'
    required: false
    default: 443
  protocol:
    description: '[ipfs] IPFS protocol'
    required: false
    default: 'https'
  headers:
    description: '[ipfs] IPFS headers as json object'
    required: false
    default: "{}"
  key:
    description: "[ipfs] IPNS key name. IPNS key will be published when the key parameter is provided. The key will be created if it does not exist"
    required: false
  pinataKey:
    description: '[pinata] Api Key. Required for pinata service'
    required: false
  pinataSecret:
    description: '[pinata] Secret Api Key. Required for pinata service'
    required: false
  pinataPinName:
    description: '[pinata] Human name for pin'
    required: false
  vercelDomain:
    description: '[vercel] Domain name. Required for vercel dnslink update'
    required: false
  vercelToken:
    description: '[vercel] Your vercel token. Required for vercel dnslink update' 
    required: false
outputs:
  hash:
    description: 'IPFS CID'
  cid:
    description: 'IPFS CID'
  ipfs:
    description: 'IPFS CID'
  ipns:
    description: 'IPNS CID if applicable'
  vercel:
    description: 'Vercel DNS record uid if applicable'
runs:
  using: 'node16'
  main: 'index.js'
